services:
  api:
    build:
      context: '.'
      dockerfile: ./docker/php-fmp/Dockerfile
    volumes:
      - .:/var/www
      - vendor_data:/var/www/vendor
    networks:
      - private_network
    # command: sh -c "php artisan migrate --force && php-fpm"
    depends_on:
      - database

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "9000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/sites-enabled/laravel.conf:/etc/nginx/sites-enabled/laravel.conf
    networks:
      - private_network
    depends_on:
      - api

  database:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - private_network

    
networks:
  private_network:
    driver: bridge

volumes:
  db_data:
  vendor_data: