apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: fiap-tc-1
type: Opaque
stringData:
  DB_DATABASE: "mecanica"
  DB_USERNAME: "mecanica"
  DB_PASSWORD: "0c88834aa9437fdb1eadb1ce1ba18cfc7d909"
  DB_ROOT_PASSWORD: "36995fe22f42b320e5cd7772c51f77ab"
  APP_KEY: "base64:87VHW9xflnIRnFqwzHcgTs2up1G2fwpE5H1tULgLvHM="
  JWT_SECRET: "cbc2908dd731105c6857860262855b46dea8acedf058cc7506b7b0221fadc4a8"
  APPROVAL_SECRET: "380fafd537df281ac624fb71eeff8a48"
