apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - storageclass-auto-ebs.yaml
  - ingressclassparams-alb.yaml
  - nodepool-t3medium.yaml

patches:
  - path: patch-mysql-pvc.yaml
  - path: patch-ingress-alb.yaml
