apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: fiap-tc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Reconsiderar o tamanho do volume ao pensar em produção
