apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: fiap-tc-1
data:
  default.conf: |
    include /etc/nginx/sites-enabled/*;
  laravel.conf: |
    upstream api_backend {
        server api:9000;
    }

    server {
        listen 80;
        server_name localhost;

        root /var/www/public;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;

            fastcgi_pass api_backend;

            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        location /nginx_status {
            stub_status;
            allow all;
        }
    }
